# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Les publics de la culture et des médias en pratiques
subtitle: Actualités de la recherche sur la réception
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rt14-afs.github.io" # the base hostname & protocol for your site
contact: http://www.test-afs-socio.fr/drupal/RT14


# Build settings
markdown: kramdown
